title: Vivas Bedriftsbehandling
subtitle: Vår visjon er at dine ansatte får en smertefri og behagelig hverdag
lang: nb
email: eplehans@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Vi er en landsdekkende tilbyder av bedriftsbehandling innen massasje, naprapati og fysioterapi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vivas.no" # the base hostname & protocol for your site, e.g. http://example.com
seo_keywords: naprapat bedriftsbehandling fysioterapi massasje manuellterapi

# Build settings

destination: docs
plugins:
  - jekyll-feed
  
# permalink: pretty
markdown: kramdown

# Sass settings
sass:
  sass_dir: style
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/